POST http://localhost:3000/api/bookings
Content-Type: application/json

{
  "name": "Andrew Tate",
  "phone": "7738145649",
  "email": "test@example.com",
  "service": "Buzzcut",
  "price": "$10.00",
  "startDate": "2026-07-15T14:00:00",
  "endDate": "2026-07-15T14:30:00",
  "notes": "test booking"
}

###

GET http://localhost:3000/api/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzgzODA1NTk3LCJleHAiOjE3ODQ0MTAzOTd9.t8N0YmItFlc3ylNe8pMDOLtFakCvz390KrfL3JMyJmM

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "chrishaircut07@gmail.com",
  "password": "Fishes123"
}

###

GET http://localhost:3000/api/reviews/reviewable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzgzODkyNjY3LCJleHAiOjE3ODQ0OTc0Njd9.yrUl8EBE4flBX_hYuZ4jOydl6pji0jPVL874EVJ3Jss

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "befferyjezos42@gmail.com",
  "password": "!C0wboys671"
}